package com.neasaa.codegenerator;

public enum CodeGeneratorMode {
	DB_TABLE_LIST, DB_TABLE_DETAILS, TABLE_CREATE_ENTITY_CLASS, TABLE_CREATE_ROWMAPPER_CLASS,
	TABLE_CREATE_DAO_CLASS, UPDATE_CLASS_HEADER
}
